CW_Django_Sending/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sending.urls', namespace='sending')),
    path('message/', include('message.urls', namespace='message')),
    path('clients/', include('clients.urls', namespace='client')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('service/', include('service.urls', namespace='service')),
    path('appointment/', include('appointment.urls', namespace='appointment')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctors/urls.py
from django.urls import path
from doctors.apps import DoctorsConfig
from doctors.views import DoctorListView, DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView

app_name = DoctorsConfig.name


urlpatterns = [
    path('', DoctorListView.as_view(), name='doctor_list'),
    path('<int:pk>/', DoctorDetailView.as_view(), name='doctor_view'),
    path('create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('edit/<int:pk>/', DoctorUpdateView.as_view(), name='doctor_edit'),
    path('delete/<int:pk>/', DoctorDeleteView.as_view(), name='doctor_delete'),
]

message/urls.py
from django.urls import path

from message.apps import MessageConfig
from message.views import MessageListView, MessageDetailView, MessageCreateView, MessageUpdateView, MessageDeleteView

app_name = MessageConfig.name


urlpatterns = [
    path('', MessageListView.as_view(), name='message_list'),
    path('<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('create/', MessageCreateView.as_view(), name='message_create'),
    path('edit/<int:pk>/', MessageUpdateView.as_view(), name='message_edit'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
]

sending/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from sending.apps import SendingConfig
from sending.views import SendingListView, SendingDetailView, SendingCreateView, SendingUpdateView, SendingDeleteView, \
    get_mailing_status, home
from . import views
app_name = SendingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('list/', SendingListView.as_view(), name='sending_list'),
    path('<int:pk>/', SendingDetailView.as_view(), name='sending_view'),
    path('create/', SendingCreateView.as_view(), name='sending_create'),
    path('edit/<int:pk>/', SendingUpdateView.as_view(), name='sending_edit'),
    path('delete/<int:pk>/', SendingDeleteView.as_view(), name='sending_delete'),
    path('start_all_mailings/', views.start_all_mailings, name='start_all_mailings'),
    path('stop_all_mailings/', views.stop_all_mailings, name='stop_all_mailings'),
    path('get_mailing_status/', get_mailing_status, name='get_mailing_status'),
    path('contacts/', views.contacts, name='contacts'),
]

service/urls.py
from django.urls import path
from service.apps import ServiceConfig
from service.views import ServiceCreateView, ServiceListView, ServiceDetailView, ServiceUpdateView, ServiceDeleteView

app_name = ServiceConfig.name


urlpatterns = [
    path('', ServiceListView.as_view(), name='service_list'),
    path('<int:pk>/', ServiceDetailView.as_view(), name='service_view'),
    path('create/', ServiceCreateView.as_view(), name='service_create'),
    path('edit/<int:pk>/', ServiceUpdateView.as_view(), name='service_edit'),
    path('delete/<int:pk>/', ServiceDeleteView.as_view(), name='service_delete'),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, password_reset_request, UserListView, ban_user, unban_user, \
    CustomLoginView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='users/login.html', next_page='/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password-reset/', password_reset_request, name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('', UserListView.as_view(), name='user_list'),
    path('ban/<int:user_id>/', ban_user, name='ban_user'),
    path('unban/<int:user_id>/', unban_user, name='unban_user'),
]

sending/models.py
from django.db import models
from datetime import datetime, timedelta
from config.settings import PERIOD_CHOICES, STATUS_CHOICES, NULLABLE, MANAGER_PERMISSIONS
from clients.models import Client



class Sending(models.Model):
    def default_sending_name():
        return 'Рассылка от ' + datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    name = models.CharField(max_length=150, verbose_name='Название рассылки', default=default_sending_name)
    datetime = models.DateTimeField(verbose_name='Дата и время первой отправки', auto_now_add=True)
    period = models.CharField(max_length=50, choices=PERIOD_CHOICES, verbose_name='Периодичность')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, verbose_name='Статус рассылки', default='created')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    message = models.ForeignKey('message.Message', on_delete=models.CASCADE, verbose_name='Сообщение')
    number_of_parcels = models.IntegerField(verbose_name='Количество писем', default=1)
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Владелец', related_name='sendings', editable=False)

    def calculate_next_datetime(self):
        if self.period == 'minute':
            return self.datetime + timedelta(minutes=1)
        elif self.period == 'daily':
            return self.datetime + timedelta(days=1)
        elif self.period == 'weekly':
            return self.datetime + timedelta(weeks=1)
        elif self.period == 'monthly':
            return self.datetime + timedelta(days=30)
        return self.datetime

    def __str__(self):
        return f"{self.datetime} {self.status}"

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = MANAGER_PERMISSIONS

class MailingStatus(models.Model):
    is_running = models.BooleanField(default=True)

    def __str__(self):
        return f"Mailing is {'running' if self.is_running else 'stopped'}"

    class Meta:
        verbose_name = 'Статус рассылки'
        verbose_name_plural = 'Статусы рассылок'



class SendAttempt(models.Model):
    datetime = models.DateTimeField(verbose_name='Дата и время попытки', db_index=True)
    status = models.BooleanField(verbose_name='Статус попытки')
    response = models.TextField(**NULLABLE, verbose_name='Ответ почтового сервера')
    sending = models.ForeignKey(Sending, on_delete=models.CASCADE, related_name='attempts', verbose_name='Рассылка', default=1)
    story_attempt = models.TextField(verbose_name='История попыток', default='Не было рассылки пока')

    def __str__(self):
        return f"{self.datetime} {self.status}"

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

sending/forms.py
from django.forms import ModelForm, BooleanField
from django import forms

from clients.models import Client
from sending.models import Sending


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'




class SendingForm(StyleFormMixin, ModelForm):
    clients = forms.ModelMultipleChoiceField(
        queryset=Client.objects.none(),
        widget=forms.SelectMultiple,
        required=True
    )
    class Meta:
        model = Sending
        fields = '__all__'

class SendingManagerForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Sending
        fields = ['status']

class FeedbackForm(forms.Form):
    name = forms.CharField(max_length=100, label='Ваше имя')
    email = forms.EmailField(label='Ваш email')
    message = forms.CharField(widget=forms.Textarea, label='Сообщение')

sending/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from blog.models import Blog
from clients.models import Client
from doctors.models import Doctor
from sending.forms import SendingForm, SendingManagerForm
from sending.models import Sending, MailingStatus
from sending.services import send_mailing
from service.models import Service
from django.shortcuts import render
from .forms import FeedbackForm
from django.core.mail import send_mail


@csrf_exempt
@require_POST
def start_all_mailings(request):
    """Запуск всех рассылок через страницу"""
    try:
        status = MailingStatus.objects.first()
        if status:
            status.is_running = True
            status.save()
        else:
            MailingStatus.objects.create(is_running=True)
        send_mailing()
        return JsonResponse({'status': 'success', 'service': 'Рассылки запущены'})
    except Exception as e:
        return JsonResponse({'status': 'error', 'service': str(e)})

@csrf_exempt
@require_POST
def stop_all_mailings(request):
    """Остановка всех рассылок через страницу"""
    status = MailingStatus.objects.first()
    if status:
        status.is_running = False
        status.save()
    return JsonResponse({'status': 'success', 'service': 'Рассылки остановлены'})


def get_mailing_status(request):
    """Получение статуса рассылок для отображения на странице"""
    status = MailingStatus.objects.first()
    if status and status.is_running:
        return JsonResponse({'status': 'running', 'service': 'Рассылки запущены'})
    return JsonResponse({'status': 'stopped', 'service': 'Рассылки остановлены'})

class SendingListView(LoginRequiredMixin, ListView):
    model = Sending


class SendingDetailView(LoginRequiredMixin, DetailView):
    model = Sending


class SendingCreateView(LoginRequiredMixin, CreateView):
    model = Sending
    form_class = SendingForm
    success_url = reverse_lazy('sending:sending_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.all()  # Показываем всех клиентов
        return form


class SendingUpdateView(LoginRequiredMixin, UpdateView):
    model = Sending
    form_class = SendingForm

    def get_success_url(self):
        return reverse('sending:sending_view', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        sending = form.save(commit=False)
        if not sending.owner:
            sending.owner = self.request.user
        sending.slug = slugify(sending.name)
        sending.save()
        form.save_m2m()
        return super().form_valid(form)

    def get_form(self, form_class=None):
        """Обновляем queryset клиентов в форме"""
        form = super().get_form(form_class)
        form.fields['clients'].queryset = Client.objects.all()
        return form

class SendingDeleteView(DeleteView):
    model = Sending
    success_url = reverse_lazy('sending:sending_list')
    extra_context = {
        'title': 'Delete Sending'
    }

def home(request):
    """Получение общей информации для главной страницы и обработка формы обратной связи"""
    total_mailings = Sending.objects.count()
    active_mailings = Sending.objects.filter(status='active').count()
    unique_clients = Client.objects.distinct().count()
    random_articles = Blog.objects.order_by('?')[:3]
    total_doctors = Doctor.objects.count()
    total_services = Service.objects.count()

    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_mail(
                f'Feedback from {name}',
                message,
                '9272060714@mail.ru',
                ['kulob3@yandex.ru'],
                fail_silently=False,
            )
            return redirect('home')
    else:
        form = FeedbackForm()

    context = {
        'total_mailings': total_mailings,
        'active_mailings': active_mailings,
        'unique_clients': unique_clients,
        'random_articles': random_articles,
        'total_doctors': total_doctors,
        'total_services': total_services,
        'form': form,
    }
    return render(request, 'sending/home.html', context)



def contacts(request):
    """Функция страницы контактов и формы обратной связи"""
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            send_mail(
                f'Feedback from {name}',
                message,
                '9272060714@mail.ru',
                ['kulob3@yandex.ru'],
                fail_silently=False,
            )
            return redirect('contacts')
    else:
        form = FeedbackForm()

    context = {
        'form': form,
    }
    return render(request, 'sending/contacts.html', context)

sending/templates/sending/base.html
{% load static %}
{% load custom_filters %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% if title %}{{ title }} - {% endif %}Медицинская клиника</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prising.css' %}" rel="stylesheet">
    <style>
        /* Additional Styling */
        .navbar-nav .nav-link {
            padding: 0.5rem 1rem;
            transition: color 0.3s;
        }

        .navbar-nav .nav-link:hover {
            color: #007bff;
        }

        .navbar-brand {
            transition: color 0.3s;
        }

        .navbar-brand:hover {
            color: #007bff;
        }

        .action-buttons .btn {
            margin: 0.5rem;
        }

        .footer {
            background-color: #f8f9fa;
            padding: 2rem 0;
        }

        .footer .text-muted {
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'sending:home' %}">Главная</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    {% if user.is_superuser or user|has_manager_perms %}
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'doctors:doctor_list' %}">Врачи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'service:service_list' %}">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1"
                               href="{% url 'appointment:appointment_list' %}">Прием врачей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'blog:blog_list' %}">Блог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'sending:sending_list' %}">Рассылки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'message:message_list' %}">Сообщения</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'clients:client_list' %}">Клиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'users:user_list' %}">Пользователи</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'clients:client_list' %}">Личный
                                кабинет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'doctors:doctor_list' %}">Врачи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'service:service_list' %}">Услуги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1"
                               href="{% url 'appointment:appointment_list' %}">Прием врачей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'blog:blog_list' %}">Блог</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1"
                           href="{% url 'sending:contacts' %}">Контакты</a>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-danger mx-1" href="{% url 'users:logout' %}">Выход</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1"
                           href="{% url 'doctors:doctor_list' %}">Врачи</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1"
                           href="{% url 'service:service_list' %}">Услуги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1" href="{% url 'blog:blog_list' %}">Блог</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-success mx-1" href="{% url 'users:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1"
                           href="{% url 'users:register' %}">Регистрация</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-primary mx-1"
                           href="{% url 'sending:contacts' %}">Контакты</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <div class="text-center mb-4">
        <h1 class="display-4">{{ title }}</h1>
    </div>
    <div class="d-flex justify-content-center mb-4 action-buttons">
    </div>
    <div class="card-deck mb-3 text-center">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="footer mt-5 border-top">
        <div class="row">
            <div class="col-12 text-center">
                <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt=""
                     width="24" height="24">
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
        </div>
    </footer>
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJQe2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGaHf0jv0g5vYdkt4tBYf0h5iT"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTIgKLL0GUDhNlgHddAN8NE2M1XcltX2c5O2JFu2BshdPH+pJ7"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.9/holder.min.js"></script>
<script>
    Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
    });
</script>
</body>
</html>

sending/templates/sending/sending_confirm_delete.html
{% extends 'sending/base.html' %}

{% block content %}
    <div class="container mt-5">
        <h2 class="mb-4"></h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
            </div>
            <h4>Delete {{ object.title }}?</h4>
            <button type="submit" class="btn btn-primary">Да</button>
            <a class="btn btn-primary" href="{% url 'sending:sending_view' object.pk %}">Нет</a>

        </form>
    </div>
{% endblock %}

sending/templates/sending/sending_detail.html
{% extends 'sending/base.html' %}
{% load custom_filters %}
{% block content %}

    <div class="card">
        <div class="card-header">{{ object.name }}</div>
        <div class="card-body">
            <p> Начало отправки {{ object.datetime }}</p>
            <p> Периодичность: {{ object.period|get_period_display }}</p>
            <p> Статус: {{ object.get_status_display }}</p>
            <p> Клиенты: {% for client in object.clients.all %}{{ client.email }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
            <p> Сообщение: {{ object.message }}</p>
            <p> Количество писем: {{ object.number_of_parcels }}</p>
            <p> Создано пользователем: {{ object.owner }}</p>

            <h3>Подробности попыток рассылки:</h3>
            <ul>
                {% for attempt in object.attempts.all %}
                    <li>
                        <strong>Дата и время:</strong> {{ attempt.datetime }}<br>
                        <strong>Статус:</strong> {{ attempt.status|yesno:"Успешно,Неудачно" }}<br>
                        <strong>Ответ почтового сервера:</strong> {{ attempt.response }}<br>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="card-footer">
            <a href="{% url 'sending:sending_edit' object.pk %}" class="btn btn-secondary">Редактировать</a>
            <a href="{% url 'sending:sending_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'sending:sending_list' %}" class="btn btn-primary">Назад</a>
        </div>
    </div>

{% endblock %}

sending/templates/sending/sending_list.html
{% extends "sending/base.html" %}
{% load custom_filters %}
{% block content %}
        <div class="d-flex justify-content-center mb-4">
        {% if user.is_authenticated %}
            <a href="{% url 'sending:sending_create' %}" class="btn btn-lg btn-primary mx-2"
               style="font-size: 1.2em; padding: 10px 20px;">
            Создать новую рассылку
        {% endif %}
        </a>
    </div>
    <div class="container mt-4">
        <div class="d-flex justify-content-between mb-3">
            {% if user.is_authenticated or user.is_superuser %}
                <button id="start-mailing-btn" class="btn btn-success"
                        style="background-color: #71dd8a; color: white; border: none;">Запуск рассылок
                </button>
                <button id="stop-mailing-btn" class="btn btn-danger"
                        style="background-color: red; color: white; border: none;">Остановка рассылок
                </button>
            {% endif %}
        </div>
        <div id="mailing-status"></div>
        <div class="row">
            <div class="col-md-12">
                <h1 class="h2">Список рассылок</h1>
            </div>
            {% if user.is_superuser or user|has_manager_perms %}
                {% for object in object_list %}
                    <div class="col-md-4">
                        <div class="card mb-4 box-shadow">
                            <div class="card-header">
                                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Статус: {{ object.get_status_display }}</h5>
                                <p class="card-text">Тема сообщения: {{ object.message }}</p>
                                <a href="{% url 'sending:sending_view' object.pk %}" class="btn btn-primary btn-block">Просмотр</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                {% for object in object_list %}
                    {% if object.owner == user %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <div class="card-header">
                                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title">Статус: {{ object.get_status_display }}</h5>
                                    <p class="card-text">Тема сообщения: {{ object.message }}</p>
                                    <a href="{% url 'sending:sending_view' object.pk %}"
                                       class="btn btn-primary btn-block">Просмотр</a>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <script>
        document.getElementById('start-mailing-btn').addEventListener('click', function () {
            fetch("{% url 'sending:start_all_mailings' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    const statusDiv = document.getElementById('mailing-status');
                    if (data.status === 'success') {
                        statusDiv.innerHTML = `<div class="alert alert-success">${data.message}</div>`;
                    } else {
                        statusDiv.innerHTML = `<div class="alert alert-danger">${data.message}</div>`;
                    }
                })
                .catch(error => {
                    document.getElementById('mailing-status').innerHTML = `<div class="alert alert-danger">An error occurred: ${error}</div>`;
                });
        });

        document.getElementById('stop-mailing-btn').addEventListener('click', function () {
            fetch("{% url 'sending:stop_all_mailings' %}", {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json'
                }
            })
                .then(response => response.json())
                .then(data => {
                    const statusDiv = document.getElementById('mailing-status');
                    if (data.status === 'success') {
                        statusDiv.innerHTML = `<div class="alert alert-success">${data.message}</div>`;
                    } else {
                        statusDiv.innerHTML = `<div class="alert alert-danger">${data.message}</div>`;
                    }
                })
                .catch(error => {
                    document.getElementById('mailing-status').innerHTML = `<div class="alert alert-danger">An error occurred: ${error}</div>`;
                });
        });

        function fetchMailingStatus() {
            fetch("{% url 'sending:get_mailing_status' %}")
                .then(response => response.json())
                .then(data => {
                    const statusDiv = document.getElementById('mailing-status');
                    if (data.status === 'running') {
                        statusDiv.innerHTML = `<div class="alert alert-success">${data.message}</div>`;
                    } else {
                        statusDiv.innerHTML = `<div class="alert alert-danger">${data.message}</div>`;
                    }
                })
                .catch(error => {
                    document.getElementById('mailing-status').innerHTML = `<div class="alert alert-danger">An error occurred: ${error}</div>`;
                });
        }

        setInterval(fetchMailingStatus, 5000);
    </script>
{% endblock %}