CW_Django_Sending/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

appointment/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from appointment.apps import AppointmentConfig
from appointment.views import AppointmentCreateView, AppointmentListView, AppointmentDetailView, AppointmentUpdateView, \
    AppointmentDeleteView, cancel_appointment, confirm_appointment

app_name = AppointmentConfig.name

urlpatterns = [
    path('create/', AppointmentCreateView.as_view(), name='appointment_create'),
    path('', AppointmentListView.as_view(), name='appointment_list'),
    path('view/<int:pk>/', cache_page(60)(AppointmentDetailView.as_view()), name='appointment_view'),
    path('edit/<int:pk>/', AppointmentUpdateView.as_view(), name='appointment_edit'),
    path('delete/<int:pk>/', AppointmentDeleteView.as_view(), name='appointment_delete'),
    path('cancel/<int:pk>/', cancel_appointment, name='appointment_cancel'),
    path('<int:pk>/confirm/', confirm_appointment, name='appointment_confirm'),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sending.urls', namespace='sending')),
    path('message/', include('message.urls', namespace='message')),
    path('clients/', include('clients.urls', namespace='client')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('service/', include('service.urls', namespace='service')),
    path('appointment/', include('appointment.urls', namespace='appointment')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointment/models.py
from django.db import models
from dirtyfields import DirtyFieldsMixin
from config.settings import NULLABLE, APPOINTMENT_STATUS_CHOICES
from doctors.models import Doctor
from service.models import Service
from clients.models import Client

def default_appointment_name():
    return 'Запись на прием'

class Appointment(DirtyFieldsMixin, models.Model):
    name = models.CharField(max_length=150, verbose_name='Наименование', default=default_appointment_name)
    client = models.ForeignKey('clients.Client', on_delete=models.CASCADE, verbose_name='Клиент')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name='Услуга')
    appointment_number_int = models.IntegerField(verbose_name='Номер записи', null=True)
    date = models.DateField(verbose_name='Дата')
    time = models.TimeField(verbose_name='Время')
    price = models.ForeignKey('service.Service', on_delete=models.CASCADE, verbose_name='Цена', related_name='appointment_prices')
    status = models.CharField(max_length=150, verbose_name='Статус', choices=APPOINTMENT_STATUS_CHOICES, default='Новый')
    comment = models.TextField(verbose_name='Комментарий', **NULLABLE)
    result = models.TextField(verbose_name='Результат', **NULLABLE)

    class Meta:
        verbose_name = 'Прием врача'
        verbose_name_plural = 'Прием врачей'

    def __str__(self):
        return f'{self.client} - {self.date}'

    def save(self, *args, **kwargs):
        if not self.name or self.name == 'Запись на прием':
            super().save(*args, **kwargs)
            self.name = f'Запись на прием {self.id}'
        super().save(*args, **kwargs)

appointment/forms.py
from django.forms import ModelForm, BooleanField, DateInput, TimeInput
from appointment.models import Appointment


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class AppointmentForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Appointment
        exclude = ['name', 'client', 'appointment_number_int', 'price', 'status']
        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
            'time': TimeInput(attrs={'type': 'time'}),
        }

class AdminAppointmentForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Appointment
        exclude = ['appointment_number_int']
        widgets = {
            'date': DateInput(attrs={'type': 'date'}),
            'time': TimeInput(attrs={'type': 'time'}),
        }

appointment/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from appointment.forms import AppointmentForm, AdminAppointmentForm
from appointment.models import Appointment
from django.shortcuts import get_object_or_404
from clients.models import Client
from django.shortcuts import redirect
from django.contrib import messages


class AppointmentListView(LoginRequiredMixin, ListView):
    model = Appointment
    template_name = "appointment/appointment_list.html"
    context_object_name = "appointments"

    def get_queryset(self):
        user = self.request.user
        if user.is_superuser or user.groups.filter(name='manager').exists():
            return Appointment.objects.all()  # Админы и менеджеры видят все записи

        # Проверяем, есть ли у пользователя объект Client
        client = Client.objects.filter(email=user).first()
        if client:
            return Appointment.objects.filter(client=client)  # Клиент видит только свои записи

        return Appointment.objects.none()  # Если клиент не найден, ничего не показываем

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["client"] = Client.objects.filter(email=self.request.user).first()
        return context


class AppointmentDetailView(LoginRequiredMixin, DetailView):
    model = Appointment


class AppointmentCreateView(LoginRequiredMixin, CreateView):
    model = Appointment
    success_url = reverse_lazy('appointment:appointment_list')

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or hasattr(user, 'is_manager') and user.is_manager:
            return AdminAppointmentForm
        return AppointmentForm

    def form_valid(self, form):
        user = self.request.user
        client = get_object_or_404(Client, email=user)  # Ищем по объекту User, а не строке email
        form.instance.client = client
        form.instance.price = form.cleaned_data['service']
        return super().form_valid(form)


class AppointmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Appointment
    form_class = AppointmentForm

    def get_form_class(self):
        user = self.request.user
        if user.is_superuser or hasattr(user, 'is_manager') and user.is_manager:
            return AdminAppointmentForm
        return AppointmentForm

    def form_valid(self, form):
        if 'cancel_appointment' in self.request.POST:
            form.instance.status = 'Отменен'
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('appointment:appointment_view', args=[self.object.pk])


class AppointmentDeleteView(LoginRequiredMixin, DeleteView):
    model = Appointment
    success_url = reverse_lazy('appointment:appointment_list')
    extra_context = {
        'title': 'Delete appointment'
    }

def cancel_appointment(request, pk):
    """Функция отмены приема"""
    appointment = get_object_or_404(Appointment, pk=pk)
    appointment.status = 'Отменен'
    appointment.save()
    messages.success(request, 'Appointment has been cancelled.')
    return redirect('appointment:appointment_view', pk=pk)


def confirm_appointment(request, pk):
    """Функция подтверждения приема менеджером"""
    appointment = get_object_or_404(Appointment, pk=pk)
    appointment.status = 'Подтвержден'
    appointment.save()
    messages.success(request, 'Appointment has been confirmed.')
    return redirect('appointment:appointment_view', pk=pk)

appointment/templates/appointment/appointment_confirm_delete.html
{% extends 'sending/base.html' %}

{% block content %}
    <div class="container mt-5">
        <h2 class="mb-4"></h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
            </div>
            <h4>Удалить запись {{ object.name }} на {{ object.date }}?</h4>
            <button type="submit" class="btn btn-primary">Да</button>
            <a class="btn btn-primary" href="{% url 'appointment:appointment_view' object.pk %}">Нет</a>
        </form>
    </div>
{% endblock %}

appointment/templates/appointment/appointment_detail.html
{% extends 'sending/base.html' %}
{% load appointment_filter %}
{% block content %}

    <div class="card">
        <div class="card-header"> Прием врача: {{ object.name }}</div>
        <div class="card-body">
            <p> Клиент: {{ object.client }}</p>
            <p> Услуга: {{ object.service }}</p>
            <p> Дата: {{ object.date }}</p>
            <p> Время: {{ object.time }}</p>
            <p> Статус: {{ object.get_status_display }}</p>
            <p> Комментарий: {{ object.comment }}</p>
            <p> Результат: {{ object.result }}</p>
        </div>
        <div class="card-footer">
            {% if user.is_superuser or user|has_manager_perms %}
            <a href="{% url 'appointment:appointment_edit' object.pk %}" class="btn btn-secondary">Редактировать</a>
            <a href="{% url 'appointment:appointment_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            <a href="{% url 'appointment:appointment_confirm' object.pk %}" class="btn btn-success" {% if object|is_confirmed %}disabled{% endif %}>Подтвердить</a>
            {% endif %}
            {% if object.client %}
            <a href="{% url 'appointment:appointment_cancel' object.pk %}" class="btn btn-warning">Отменить</a>
            {% endif %}
            <a href="{% url 'appointment:appointment_list' %}" class="btn btn-outline-dark">Назад</a>
        </div>
    </div>

{% endblock %}

appointment/templates/appointment/appointment_form.html
{% extends 'sending/base.html' %}

{% block content %}
    <div class="container mt-5">
<h2 class="mb-4">{% if form.instance.pk %}Редактирование запись{% else %}Создание новой записи{% endif %}</h2>
        <form method="post" class="needs-validation" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}

appointment/templates/appointment/appointment_list.html
{% extends "sending/base.html" %}
{% load appointment_filter %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="d-flex justify-content-center mb-4">
            <a href="{% url 'appointment:appointment_create' %}" class="btn btn-lg btn-primary mx-2"
               style="font-size: 1.2em; padding: 10px 20px;">
                Запись на прием
            </a>
        </div>
    {% endif %}

    {% if user.is_superuser or user|has_manager_perms %}
        {% for object in object_list %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    <a href="{% url 'appointment:appointment_view' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">Просмотр</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        {% for object in object_list %}
    {% if object.client == client %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                <a href="{% url 'appointment:appointment_view' object.pk %}"
                   class="btn btn-lg btn-block btn-outline-primary">Просмотр</a>
            </div>
        </div>
    {% endif %}
{% endfor %}
    {% endif %}
{% endblock %}