CW_Django_Sending/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sending.urls', namespace='sending')),
    path('message/', include('message.urls', namespace='message')),
    path('clients/', include('clients.urls', namespace='client')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('service/', include('service.urls', namespace='service')),
    path('appointment/', include('appointment.urls', namespace='appointment')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sending/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from sending.apps import SendingConfig
from sending.views import SendingListView, SendingDetailView, SendingCreateView, SendingUpdateView, SendingDeleteView, \
    get_mailing_status, home
from . import views
app_name = SendingConfig.name

urlpatterns = [
    path('', home, name='home'),
    path('list/', SendingListView.as_view(), name='sending_list'),
    path('<int:pk>/', SendingDetailView.as_view(), name='sending_view'),
    path('create/', SendingCreateView.as_view(), name='sending_create'),
    path('edit/<int:pk>/', SendingUpdateView.as_view(), name='sending_edit'),
    path('delete/<int:pk>/', SendingDeleteView.as_view(), name='sending_delete'),
    path('start_all_mailings/', views.start_all_mailings, name='start_all_mailings'),
    path('stop_all_mailings/', views.stop_all_mailings, name='stop_all_mailings'),
    path('get_mailing_status/', get_mailing_status, name='get_mailing_status'),
    path('contacts/', views.contacts, name='contacts'),
]

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок', help_text='Введите заголовок блога')
    slug = models.SlugField(max_length=150, verbose_name='Slug')
    content = models.TextField(verbose_name='Содержание', help_text='Введите содержание блога')
    preview = models.ImageField(upload_to='blog/photo', verbose_name='Изображение', help_text='Загрузите изображение')
    views = models.IntegerField(default=0, verbose_name='Количество просмотров')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    owner = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name='Владелец', related_name='blog', editable=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        ordering = ['title']

blog/forms.py
from django.forms import ModelForm, BooleanField

from blog.models import Blog


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'




class BlogForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Blog
        exclude = ['slug', 'views']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'object_list'  # Приводим в соответствие с шаблоном

    def get_queryset(self):
        return Blog.objects.all()  # Делаем доступными ВСЕ записи



class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset=queryset)
        self.object.views += 1
        self.object.save()
        return self.object

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:blog_view', args=[self.kwargs.get('pk')])

class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'sending/base.html' %}

{% block action_buttons %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="mb-4"></h2>
        <form method="post" class="needs-validation" novalidate>
            {% csrf_token %}
            <div class="mb-3">
            </div>
            <h4>Удалить {{ object.name }}?</h4>
            <button type="submit" class="btn btn-primary">Да</button>
            <a class="btn btn-primary" href="{% url 'blog:blog_view' object.pk %}">Нет</a>
        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'sending/base.html' %}
{% load media_filter %}
{% block content %}

    {% block action_buttons %}
    {% endblock %}

    <div class="card">
        <div class="card-header">{{ object.title }}</div>
        <div class="card-body">
            <img src="{{ object.preview|media_filter }}" alt="Preview">
            <p> {{ object.content }}</p>
            <p> Добавлено: {{ object.created_at }}</p>
            <p> Автор: {{ object.owner }}</p>
            <p> Количество просмотров: {{ object.views }}</p>
        </div>
        <div class="card-footer">
            {% if user == object.owner or user.is_superuser %}
                <a href="{% url 'blog:blog_edit' object.pk %}" class="btn btn-secondary">Редактировать</a>
                <a href="{% url 'blog:blog_delete' object.pk %}" class="btn btn-danger">Удалить</a>
            {% endif %}
            <a href="{% if request.GET.from == 'home' %}{% url 'sending:home' %}{% else %}{% url 'blog:blog_list' %}{% endif %}" class="btn btn-outline-dark">Назад</a>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'sending/base.html' %}

{% block action_buttons %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
<h2 class="mb-4">{% if form.instance.pk %}Редактирование записи{% else %}Новая запись{% endif %}</h2>
        <form method="post" class="needs-validation" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.as_p }}
            </div>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "sending/base.html" %}
{% load media_filter %}
{% load blog_filter %}

{% block action_buttons %}
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-center mb-4">
        {% if user.is_authenticated %}
            <a href="{% url 'blog:blog_create' %}" class="btn btn-lg btn-primary mx-2"
               style="font-size: 1.2em; padding: 10px 20px;">
            Создать новую запись
        {% endif %}
        </a>
    </div>
    <div class="container">
        <div class="row">
            {% for object in object_list %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card shadow-sm border-0 h-100 d-flex flex-column">
                        <div class="card-header text-center bg-primary text-white">
                            <h4 class="font-weight-normal">{{ object.title }}</h4>
                        </div>
                        <div class="card-body text-center">
                            <img src="{{ object.preview|media_filter }}" alt="Preview" class="img-fluid mb-3"
                                 style="max-height: 200px; object-fit: cover;">
                        </div>
                        <div class="card-footer mt-auto text-center">
                            <a href="{% url 'blog:blog_view' object.pk %}" class="btn btn-outline-primary btn-block">
                                Просмотр
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}