CW_Django_Sending/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('', cache_page(60)(BlogListView.as_view()), name='blog_list'),
    path('view/<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blog_view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='blog_edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sending.urls', namespace='sending')),
    path('message/', include('message.urls', namespace='message')),
    path('clients/', include('clients.urls', namespace='client')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
    path('doctors/', include('doctors.urls', namespace='doctors')),
    path('service/', include('service.urls', namespace='service')),
    path('appointment/', include('appointment.urls', namespace='appointment')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, password_reset_request, UserListView, ban_user, unban_user, \
    CustomLoginView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', CustomLoginView.as_view(template_name='users/login.html', next_page='/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password-reset/', password_reset_request, name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('', UserListView.as_view(), name='user_list'),
    path('ban/<int:user_id>/', ban_user, name='ban_user'),
    path('unban/<int:user_id>/', unban_user, name='unban_user'),
]

users/models.py
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from config.settings import NULLABLE, MANAGER_PERMISSIONS


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    first_name = models.CharField(max_length=150, verbose_name='Имя', **NULLABLE)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия', **NULLABLE)
    phone = PhoneNumberField(unique=True, verbose_name='Номер телефона', **NULLABLE)
    avatar = models.ImageField(verbose_name='Фото', upload_to='users/avatars/', **NULLABLE)
    token = models.CharField(max_length=150, verbose_name='token', **NULLABLE)
    banned = models.BooleanField(default=False, verbose_name='Пользователь забанен')
    is_manager = models.BooleanField(default=False, verbose_name='Менеджер')
    is_client = models.BooleanField(default=False, verbose_name='Клиент')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        permissions = MANAGER_PERMISSIONS

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from sending.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'phone', 'password1', 'password2']

class PasswordResetRequestForm(forms.Form):
    email = forms.EmailField(label="Email", max_length=254)

users/views.py
import secrets
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy, reverse
from django.utils.http import urlsafe_base64_encode
from django.views.generic import CreateView, ListView
from django.utils.encoding import force_bytes
from config import settings
from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, PasswordResetRequestForm
from users.models import User
from django.contrib.auth.tokens import default_token_generator
import string
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        print(url)
        send_mail(
            subject='Email confirmation',
            message=f'Click on the link to confirm your email: {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def generate_random_password(length=12):
    """Функция для генерации случайного пароля"""
    characters = string.ascii_letters + string.digits + string.punctuation
    return ''.join(secrets.choice(characters) for i in range(length))


def password_reset_request(request):
    """Функция для сброса пароля"""
    if request.method == "POST":
        form = PasswordResetRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            associated_users = User.objects.filter(email=email)
            if associated_users.exists():
                for user in associated_users:
                    new_password = generate_random_password()
                    user.set_password(new_password)
                    user.save()

                    subject = "Password Reset Requested"
                    email_template_name = "users/password_reset_email.html"
                    c = {
                        "email": user.email,
                        'domain': get_current_site(request).domain,
                        'site_name': 'Website',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                        'new_password': new_password,
                    }
                    email = render_to_string(email_template_name, c)
                    send_mail(subject, email, settings.EMAIL_HOST_USER, [user.email], fail_silently=False)
            return redirect("users:password_reset_done")
    form = PasswordResetRequestForm()
    return render(request, "users/password_reset.html", {"form": form})


class UserListView(LoginRequiredMixin, ListView):
    model = User

class CustomLoginView(LoginView):
    """Класс для авторизации пользователя, не позволяет забаненным пользователям авторизоваться"""
    def form_valid(self, form):
        user = form.get_user()
        if user.banned:
            messages.error(self.request, 'Вы забанены.')
            return self.form_invalid(form)
        return super().form_valid(form)


@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='manager').exists())
def ban_user(request, user_id):
    """Проверка полномочий перед баном"""
    user_to_ban = get_object_or_404(User, pk=user_id)

    if request.user.is_superuser:
        if user_to_ban.is_superuser:
            messages.error(request, 'Администратор не имеет права банить администраторов.')
            return redirect('users:user_list')
    elif request.user.groups.filter(name='manager').exists():
        if user_to_ban.is_superuser or user_to_ban.groups.filter(name='manager').exists():
            messages.error(request, 'Менеджер не имеет права банить администраторов или менеджеров.')
            return redirect('users:user_list')

    user_to_ban.banned = True
    user_to_ban.save()
    messages.success(request, f'Пользователь {user_to_ban.email} забанен.')
    return redirect('users:user_list')

@user_passes_test(lambda u: u.is_superuser or u.groups.filter(name='manager').exists())
def unban_user(request, user_id):
    """Проверка полномочий перед разбаном"""
    user_to_unban = get_object_or_404(User, pk=user_id)

    if request.user.is_superuser:
        if user_to_unban.is_superuser:
            return redirect('users:user_list')
    elif request.user.groups.filter(name='manager').exists():
        if user_to_unban.is_superuser or user_to_unban.groups.filter(name='manager').exists():
            return redirect('users:user_list')

    user_to_unban.banned = False
    user_to_unban.save()
    messages.success(request, f'Пользователь {user_to_unban.email} разбанен.')
    return redirect('users:user_list')

users/templates/users/login.html
{% extends 'sending/base.html' %}
{% block content %}
    <div class="container mt-5">
        <form class="row" method="post" class="needs-validation" novalidate enctype="multipart/form-data">
            <div class="col-md-6">
                <h2 class="mb-4">Вход в сервис</h2>
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Вход</button>
            </div>
        </form>
    <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
    </div>
{% endblock %}

users/templates/users/password_reset.html
{% extends "sending/base.html" %}
{% block content %}
<h2>Сброс пароля</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сбросить мой пароль</button>
</form>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "sending/base.html" %}
{% block content %}
<h2>Сброс пароля</h2>
<p>Инструкции по сбросу пароля были отправлены на почту.</p>
    <li><a href="{% url 'users:login' %}" class="text-bg-info">Log In</a></li>
{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please use the following password to log in:" %}
{% block new_password %}
{{ new_password }}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/user_form.html
{% extends 'sending/base.html' %}
{% block content %}
    <div class="container mt-5">
        <form class="row" method="post" class="needs-validation" novalidate enctype="multipart/form-data">
            <div class="col-md-6">
                <h2 class="mb-4">Регистрация в сервисе</h2>
                {% csrf_token %}
                <div class="mb-3">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends "sending/base.html" %}
{% load users_filter %}

{% block content %}
    {% if user.is_superuser or user|has_manager_perms %}
        {% for object in object_list %}
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.email }}</h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title">Имя: {{ object.first_name }}</h5>
                    <p class="card-text">Фамилия: {{ object.last_name }}</p>
                    {% if object.banned %}<p class="card-text"> Пользователь забанен! </p>{% endif %}
                    <form method="post" action="{% url 'users:ban_user' object.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Забанить</button>
                    </form>
                    {% if object.banned %}
                    <form method="post" action="{% url 'users:unban_user' object.pk %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-success">Разбанить</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>У вас нет прав для просмотра информации на этой странице</p>
    {% endif %}
{% endblock %}